name: weekly episode deployment

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * SUN"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: curl --request POST --url '${{ secrets.DEPLOY_HOOK_URL }}'
