name: weekly episode deployment

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * SUN"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: joelwmale/webhook-action@2.1.0
        with:
          url: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
